#!/bin/bash

mkdir -p /opt/osdp-conformance/bin
mkdir -p /opt/osdp-conformance/etc
cp /opt/osdp-conformance/etc/pkoc/osdp_* /opt/osdp-conformance/actions
echo overwriting any pre-existing pkoc-settings.json
cp /opt/osdp-conformance/etc/pkoc/pkoc-settings.json /opt/osdp-conformance/etc


