#!/bin/bash
RESPONSES=/opt/osdp-conformance/responses
LOG=/opt/osdp-conformance/log
mkdir -p ${LOG}
echo >${RESPONSES}/response_MFG $2
/opt/osdp-conformance/bin/pkoc-mfg <${RESPONSES}/response_MFG $2
echo >>/opt/osdp-conformance/log/actions.log osdp_MFG called $1 $2 $3 $4 $5 $6 $7 $8




