#!/bin/bash
RESPONSES=/opt/osdp-conformance/responses
LOG=/opt/osdp-conformance/log
mkdir -p /opt/osdp-conformance/log
# arg 2 is the json blob
echo >${RESPONSES}/response_MFGREP $2
/opt/osdp-conformance/bin/pkoc-mfgrep <${RESPONSES}/response_MFGREP $2
echo >>${LOG}/actions.log osdp_MFGREP called $1 $2 $3 $4 $5 $6 $7 $8


